[package]
name = "solana-snapshot-etl"
version = "0.3.0"
edition = "2021"
license = "Apache-2.0"
documentation = "https://docs.rs/solana-snapshot-etl"
description = "Efficiently unpack Solana snapshots"
authors = ["Richard Patel <me@terorie.dev>", "Triton One"]
categories = ["cryptography::cryptocurrencies", "database"]
keywords = ["solana"]
publish = false

[dependencies]
bincode = "1.3.3"
clap = { version = "3.2.14", features = ["derive"] }
itertools = "0.10.3"
log = "0.4.17"
memmap2 = "0.5.5"
serde = { version = "1.0.139", features = ["derive"] }
solana-runtime = "1.16.12"
solana-sdk = "1.16.12"
solana-frozen-abi-macro = "1.16.12"
tar = "0.4.38"
thiserror = "1.0.31"
zstd = "0.11.2"

# Binary deps
borsh = { version = "0.9.3", optional = true }
crossbeam = { version = "0.8.2", optional = true }
csv = { version = "1.1.6", optional = true }
env_logger = { version = "0.9.0", optional = true }
indicatif = { version = "0.17.0-rc.11", optional = true }
json5 = { version = "0.4.1", optional = true }
# libloading = { version = "0.7.3", optional = true }
num_cpus = { version = "1.13.1", optional = true }
reqwest = { version = "0.11.11", features = ["blocking"], optional = true }
rusqlite = { version = "0.28.0", features = ["bundled"], optional = true }
serde_json = { version = "1.0.82", optional = true }
# solana-geyser-plugin-interface = { version = "1.16.12", optional = true }
solana-program = { version = "1.16.12", optional = true }
spl-token = { version = "3.3.0", optional = true }

[features]
default = ["standalone"]
parallel = []
standalone = [
    "borsh",
    "crossbeam",
    "csv",
    "env_logger",
    "indicatif",
    # "libloading",
    "num_cpus",
    "parallel",
    "reqwest",
    "rusqlite",
    "serde_json",
    # "solana-geyser-plugin-interface",
    "solana-program",
    "spl-token",
    "json5",
]

[[bin]]
name = "solana-snapshot-etl"
required-features = ["standalone"]
